# Generated by Django 6.0 on 2025-12-04 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('username_tg', models.CharField(max_length=255, verbose_name='Телеграм логин')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
