# Generated by Django 6.0 on 2025-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_image_product_image_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
