# Generated by Django 6.0 on 2025-12-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview', to='main.attachment'),
        ),
    ]
