# Generated by Django 6.0 on 2025-12-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_image_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_fk',
        ),
        migrations.AddField(
            model_name='product',
            name='preview_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.attachment'),
        ),
    ]
