# Generated by Django 6.0 on 2025-12-04 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_image_fk_product_preview_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
