# Generated by Django 6.0 on 2025-12-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
