# Generated by Django 6.0 on 2025-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
