# Generated by Django 6.0 on 2025-12-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
