# Generated by Django 6.0 on 2025-12-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_product_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_at'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
