# Generated by Django 6.0 on 2025-12-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
