# Generated by Django 6.0 on 2025-12-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
