# Generated by Django 6.0 on 2025-12-07 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUserAllow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(default=0, verbose_name='telegram_id')),
            ],
            options={
                'verbose_name': 'Разрешенный тг-юзер',
                'verbose_name_plural': 'Разрешенные тг-юзеры',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
