# Generated by Django 6.0 on 2025-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_categories_alter_product_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ-товар'),
        ),
    ]
