# Generated by Django 6.0 on 2025-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
