# Generated by Django 6.0 on 2025-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_product_articul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_top',
        ),
        migrations.AddField(
            model_name='product',
            name='sticker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стикер'),
        ),
    ]
