# Generated by Django 6.0 on 2025-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_product_is_top_product_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
