# Generated by Django 6.0 on 2025-12-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sticker_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стикер'),
        ),
    ]
