# Generated by Django 6.0 on 2025-12-08 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_product_sticker_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип стикера',
                'verbose_name_plural': 'Тип стикеров',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='sticker',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sticker_color',
        ),
        migrations.AddField(
            model_name='product',
            name='sticker_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stickertype'),
        ),
    ]
